### ISSUE TITLE
wget link is wrong

### ISSUE THREAD

**Issue by knuths** [hpc-carpentry/hpc-shell#11]
Should be  http://hpc-carpentry.github.io/hpc-shell/files/bash-lesson.tar.gz

**Comment by komish** [comment]
Hello! Seems like this has been fixed by merged PR #8

**Comment by psteinb** [comment]
@knuths where did you find this link? I just checked and send a fix with #12 for another hard coded URL I found. Must have slipped by sight the first time for #8. thanks for reporting.

**Comment by knuths** [comment]
I believe its here: https://hpc-carpentry.github.io/hpc-shell/03-files/index.html

**Comment by psteinb** [comment]
Indeed I fixed this with #12 and just tested it with success.

**Comment by aturner-epcc** [comment]
Closing this as this has been dealt with

**Comment by Sabryr** [comment]
(commenting here without opening a new issue as this is very much related).
The same issue is here as well :
https://hpc-carpentry.github.io/hpc-shell/04-wildcards-pipes/index.html
Under "Required files".
