### ISSUE TITLE
Add a callout for curl

### ISSUE THREAD

**Issue by symulation** [hpc-carpentry/hpc-shell#14]
Lesson 03 introduces wget.  Not every system has wget by default though (e.g. Macs).  We should have one of those yellow callout boxes to mention both curl and that there are ways of installing software (assuming they have admin control).

**Comment by psteinb** [comment]
I encourage that idea for a callout box. The comment on how to install it should be something to consider well. These kind of comments often go along the lines of 'and then you just do XYZ' which overwhelms most novice users.

**Comment by aturner-epcc** [comment]
Easy to put in the callout for curl. I think the information on adding more software if you have admin rights probably needs some discussion to get right. Could we put in some text like: 'If you do not have wget or curl on your system then please ask a helper and they will be happy to show you how you can install this (if you have admin privileges on your system) or how to download the files using a web browser.' Any better suggestions for text? I am happy to make the change and put in a PR.

**Comment by symulation** [comment]
I’m totally fine with the “ask for help if neither works”.


-John

**Comment by bkmgit** [comment]
This seems to have been addressed.
