### ISSUE TITLE
Remove 00 and 01?

### ISSUE THREAD

**Issue by ChristinaLK** [hpc-carpentry/hpc-shell#2]
I think @psteinb and I both agree they should remain in the `hpc-intro` lesson.

**Comment by psteinb** [comment]
For 01, I am still undecided as explained [here](https://github.com/hpc-carpentry/hpc-intro/issues/19#issuecomment-403400936).

**Comment by bkmgit** [comment]
Think this has been addressed, so closing it. Feel free to reopen if needed.
