### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by mattagape** [hpc-carpentry/hpc-shell#21]
Hi, on the set up page (https://hpc-carpentry.github.io/hpc-shell/setup/), the link to XQuartz for Mac users is broken.

**Comment by psteinb** [comment]
confirmed, what is the correct link? Feel free to send a PR as well.

**Comment by mattagape** [comment]
Sorry, the link is https://www.xquartz.org

**Comment by mattagape** [comment]
PS I am generating a list of typos etc as I go through the lesson, and will likely submit a PR with the corrections in.

**Comment by bkmgit** [comment]
addressed in https://github.com/hpc-carpentry/hpc-shell/pull/42

**Comment by tkphd** [comment]
Closed by #42.
