### ISSUE TITLE
repo website

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-shell#6]
Please set https://hpc-carpentry.github.io/hpc-shell/ as the repo's website.

**Comment by psteinb** [comment]
as far as I can see in the settings, this is already the case. I just spotted the wrong URL [here](https://github.com/hpc-carpentry/hpc-shell#publishing-changes-to-github--the-github-pages-website). Is there anything else I need to correct?

**Comment by tkphd** [comment]
It's properly set in the README, but for convenience, it would be nice to also set it on the main repo page next to the repo description. If you have the option, from the repo page, to edit the description and keywords, there's also a form for the web page. That's the missing location this issue is referring to. Thanks!

**Comment by ChristinaLK** [comment]
Good catch @tkphd!  Done.
