### ISSUE TITLE
Generalizing lesson material

### ISSUE THREAD

**Issue by pdoehle** [hpc-carpentry/hpc-shell#9]
While reading lesson materials, I noticed several items specific to Compute Canada. I did not submit pull requests since the discussion about [Lola](https://github.com/hpc-carpentry/hpc-intro/issues/22) affects how they are changed, but I thought it would be helpful to flag items that need to be worked into the narrative or considered for some sort of Jekyll template:

## HPC Shell
| Item | Text Example | Location | Number of Instances|
|---|---|---|---|
Cluster Name | Graham | `01-connecting.md` | 3 
University Name | University of Waterloo | `01-connecting.md` | 1
Cluster Host Name | graham.computecanada.ca | `01-connecting.md` | 3
Username | jeff | Multiple places | 38
Login Node Host Name | gra-login3 | `01-connecting.md` | 1
Scheduler Name | SLURM | `lesson-outline.md`<sup>(1)</sup> | 1

## HPC Intro
| Item | Text Example | Location | Number of Instances|
|---|---|---|---|
Login Node Host Name | gra-login3 | `11-cluster.md` | 1
Username | jeff | Multiple places | 38
Scheduler Name | SLURM | `lesson-outline.md`<sup>(1)</sup>, `11-cluster.md`, `12-scheduler.md`<sup>(1)</sup>, `13-modules.md`, `15-resources.md` | 1, 8, 1

(1) Please see [here](https://github.com/hpc-carpentry/hpc-intro/issues/39)

**Comment by ChristinaLK** [comment]
Super helpful!  Thank you @pdoehle.  @psteinb is working on some of this in hpc-intro/pull/31

**Comment by aturner-epcc** [comment]
I think the changes to allow for customisation in #13 address this issue. Anyone have any objections to me closing this issue now?

**Comment by ChristinaLK** [comment]
Nope!  I can close.
